SELECT 
    COLUMN_NAME AS `Column`,
    COLUMN_TYPE AS `Type`,
    IS_NULLABLE AS `NULLABLE`,
    COLUMN_KEY AS `KEY`,
    COLUMN_DEFAULT AS `DEFAULT`,
    EXTRA AS `Extra`,

FROM 
    INFORMATION_SCHEMA.COLUMNS

WHERE 
    TABLE_SCHEMA = DATABASE()
    AND TABLE_NAME = `BOOKS`;